import prisma from "../../db.server";

interface FactorSeed {
  code: string;
  category: string;
  subcategory: string;
  labelFr: string;
  labelEn: string;
  kgCo2PerKg?: number;
  kgCo2PerUnit?: number;
  defaultWeightG: number;
  keywords: string[];
  thresholdLow: number;
  thresholdMed: number;
  thresholdHigh: number;
  source: string;
  confidence?: number;
}

const EMISSION_FACTORS: FactorSeed[] = [
  {
    code: "textile.tshirt",
    category: "textile",
    subcategory: "tshirt",
    labelFr: "T-shirt / Haut",
    labelEn: "T-shirt / Top",
    kgCo2PerKg: 20,
    defaultWeightG: 200,
    keywords: ["tshirt", "t-shirt", "polo", "shirt", "top", "tee"],
    thresholdLow: 2,
    thresholdMed: 5,
    thresholdHigh: 10,
    source: "ADEME",
  },
  {
    code: "textile.jeans",
    category: "textile",
    subcategory: "jeans",
    labelFr: "Jean / Pantalon",
    labelEn: "Jeans / Pants",
    kgCo2PerKg: 28,
    defaultWeightG: 700,
    keywords: ["jean", "jeans", "denim", "pantalon", "pants"],
    thresholdLow: 5,
    thresholdMed: 12,
    thresholdHigh: 20,
    source: "ADEME",
  },
  {
    code: "textile.manteau",
    category: "textile",
    subcategory: "manteau",
    labelFr: "Manteau / Veste",
    labelEn: "Coat / Jacket",
    kgCo2PerKg: 22,
    defaultWeightG: 1200,
    keywords: ["manteau", "coat", "veste", "jacket", "blouson", "parka"],
    thresholdLow: 10,
    thresholdMed: 20,
    thresholdHigh: 30,
    source: "ADEME",
  },
  {
    code: "textile.chaussures",
    category: "textile",
    subcategory: "chaussures",
    labelFr: "Chaussures",
    labelEn: "Shoes",
    kgCo2PerKg: 15,
    defaultWeightG: 800,
    keywords: ["chaussures", "shoes", "sneakers", "boots"],
    thresholdLow: 5,
    thresholdMed: 10,
    thresholdHigh: 18,
    source: "ADEME",
  },
  {
    code: "electronics.smartphone",
    category: "electronics",
    subcategory: "smartphone",
    labelFr: "Smartphone",
    labelEn: "Smartphone",
    kgCo2PerUnit: 70,
    defaultWeightG: 200,
    keywords: ["smartphone", "phone", "iphone", "mobile", "téléphone"],
    thresholdLow: 20,
    thresholdMed: 50,
    thresholdHigh: 80,
    source: "GHG_PROTOCOL",
  },
  {
    code: "electronics.laptop",
    category: "electronics",
    subcategory: "laptop",
    labelFr: "Ordinateur portable",
    labelEn: "Laptop",
    kgCo2PerUnit: 350,
    defaultWeightG: 1800,
    keywords: ["laptop", "ordinateur", "computer", "macbook", "pc"],
    thresholdLow: 50,
    thresholdMed: 150,
    thresholdHigh: 300,
    source: "GHG_PROTOCOL",
  },
  {
    code: "electronics.headphones",
    category: "electronics",
    subcategory: "headphones",
    labelFr: "Casque / Écouteurs",
    labelEn: "Headphones / Earphones",
    kgCo2PerUnit: 20,
    defaultWeightG: 300,
    keywords: ["casque", "headphones", "écouteurs", "earphones", "airpods"],
    thresholdLow: 5,
    thresholdMed: 15,
    thresholdHigh: 30,
    source: "GHG_PROTOCOL",
  },
  {
    code: "food.beef",
    category: "food",
    subcategory: "beef",
    labelFr: "Boeuf / Viande rouge",
    labelEn: "Beef / Red meat",
    kgCo2PerKg: 26.6,
    defaultWeightG: 400,
    keywords: ["boeuf", "beef", "steak", "viande", "burger"],
    thresholdLow: 2,
    thresholdMed: 8,
    thresholdHigh: 15,
    source: "ADEME",
  },
  {
    code: "food.chocolate",
    category: "food",
    subcategory: "chocolate",
    labelFr: "Chocolat",
    labelEn: "Chocolate",
    kgCo2PerKg: 4.6,
    defaultWeightG: 100,
    keywords: ["chocolat", "chocolate", "cacao"],
    thresholdLow: 1,
    thresholdMed: 3,
    thresholdHigh: 6,
    source: "ADEME",
  },
  {
    code: "food.coffee",
    category: "food",
    subcategory: "coffee",
    labelFr: "Café",
    labelEn: "Coffee",
    kgCo2PerKg: 8.3,
    defaultWeightG: 250,
    keywords: ["café", "coffee", "espresso", "capsule"],
    thresholdLow: 1,
    thresholdMed: 3,
    thresholdHigh: 6,
    source: "ADEME",
  },
  {
    code: "furniture.wood",
    category: "furniture",
    subcategory: "wood",
    labelFr: "Meuble en bois",
    labelEn: "Wood furniture",
    kgCo2PerKg: 1.8,
    defaultWeightG: 15000,
    keywords: ["meuble", "furniture", "table", "chaise", "chair", "bureau", "desk"],
    thresholdLow: 10,
    thresholdMed: 30,
    thresholdHigh: 60,
    source: "ADEME",
  },
  {
    code: "beauty.skincare",
    category: "beauty",
    subcategory: "skincare",
    labelFr: "Soin visage / corps",
    labelEn: "Skincare",
    kgCo2PerKg: 4.2,
    defaultWeightG: 100,
    keywords: ["soin", "skincare", "crème", "cream", "sérum", "lotion"],
    thresholdLow: 0.2,
    thresholdMed: 0.8,
    thresholdHigh: 2,
    source: "ESTIMATED",
  },
  {
    code: "sports.bike",
    category: "sports",
    subcategory: "bike",
    labelFr: "Vélo",
    labelEn: "Bicycle",
    kgCo2PerUnit: 120,
    defaultWeightG: 10000,
    keywords: ["vélo", "bike", "bicycle", "vtt", "bmx"],
    thresholdLow: 30,
    thresholdMed: 80,
    thresholdHigh: 150,
    source: "ESTIMATED",
  },
  {
    code: "books.book",
    category: "books",
    subcategory: "book",
    labelFr: "Livre",
    labelEn: "Book",
    kgCo2PerKg: 1.8,
    defaultWeightG: 400,
    keywords: ["livre", "book", "magazine", "roman"],
    thresholdLow: 0.3,
    thresholdMed: 0.8,
    thresholdHigh: 2,
    source: "ADEME",
  },
  {
    code: "toys.plastic",
    category: "toys",
    subcategory: "plastic",
    labelFr: "Jouet en plastique",
    labelEn: "Plastic toy",
    kgCo2PerKg: 4.5,
    defaultWeightG: 300,
    keywords: ["jouet", "toy", "jeu", "game", "kids", "enfant"],
    thresholdLow: 0.5,
    thresholdMed: 2,
    thresholdHigh: 5,
    source: "ESTIMATED",
  },
  {
    code: "generic.default",
    category: "generic",
    subcategory: "default",
    labelFr: "Produit générique",
    labelEn: "Generic product",
    kgCo2PerKg: 5,
    defaultWeightG: 500,
    keywords: [],
    thresholdLow: 1,
    thresholdMed: 3,
    thresholdHigh: 8,
    source: "ESTIMATED",
    confidence: 0.3,
  },
];

export async function seedEmissionFactors(): Promise<number> {
  let count = 0;

  for (const f of EMISSION_FACTORS) {
    await prisma.emissionFactor.upsert({
      where: { code: f.code },
      create: {
        code: f.code,
        category: f.category,
        subcategory: f.subcategory,
        labelFr: f.labelFr,
        labelEn: f.labelEn,
        kgCo2PerKg: f.kgCo2PerKg ?? null,
        kgCo2PerUnit: f.kgCo2PerUnit ?? null,
        defaultWeightG: f.defaultWeightG,
        thresholdLow: f.thresholdLow,
        thresholdMed: f.thresholdMed,
        thresholdHigh: f.thresholdHigh,
        source: f.source,
        confidence: f.confidence ?? 0.7,
        keywords: JSON.stringify(f.keywords),
      },
      update: {
        category: f.category,
        subcategory: f.subcategory,
        labelFr: f.labelFr,
        labelEn: f.labelEn,
        kgCo2PerKg: f.kgCo2PerKg ?? null,
        kgCo2PerUnit: f.kgCo2PerUnit ?? null,
        defaultWeightG: f.defaultWeightG,
        thresholdLow: f.thresholdLow,
        thresholdMed: f.thresholdMed,
        thresholdHigh: f.thresholdHigh,
        source: f.source,
        confidence: f.confidence ?? 0.7,
        keywords: JSON.stringify(f.keywords),
      },
    });
    count++;
  }

  return count;
}
